version: '4.4'

services:
  db:
    image: mysql:8.0
    container_name: db_papas_pizzeria
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: papaspizzeria1975
      MYSQL_DATABASE: papas_pizzeria
      MYSQL_USER: papasuser
      MYSQL_PASSWORD: papas1975
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always

volumes:
  db_data: